### ISSUE TITLE
Error loading shared library libmpc.so, libmpfr.so and libgmp.so

### ISSUE THREAD

**Issue by jimmyh98** [ps2dev/ps2dev#29]
Hello everyone, I'm trying to compile the hello.c example but I'm having problems. I had to add the make by the command "apk add make" in the container but when I do a "make all" I get the following error.

`mips64r5900el-ps2-elf-gcc -D_EE -O2 -G0 -Wall  -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ps2sdk/common/include -I.  -c hello.c -o hello.o
Error loading shared library libmpc.so.3: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1)
Error loading shared library libmpfr.so.6: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1)
Error loading shared library libgmp.so.10: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1)
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_hypot: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_cmp: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_set_emin: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_atan: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_get_version: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_exp2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_asinh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_max: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_log1p: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_snprintf: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_div: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_cbrt: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_atan2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_mul: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_j0: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_underflow_p: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_set_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_exp10: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_exp: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_pow: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_clear: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_log2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_init2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_set_erangeflag: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_pow: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_lgamma: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_asinh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_sqrt_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_inits: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_cos: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_gamma: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_remainder: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_log10: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_tanh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_add: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_clears: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_set: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_get_version: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_set_si_2exp: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_sizeinbase: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_yn: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_set_str: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_free_str: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_sqrt: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_erfc: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_j1: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_set_inf: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_sin_cos: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_remquo: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_sin: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_inits2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_fdiv_q: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_set_emax: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_tan: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_tanh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_get_str: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_acosh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_set_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_sinh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_atan: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_acosh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_init2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_jn: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_clear_flags: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_clear: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_export: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_com: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_number_p: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_log: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_exp: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_cos: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_swap: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_set_nan: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_import: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_sub_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_fma: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_sinh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_sub: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_init_set: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_sub: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_atanh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_init: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_sqrt: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_sub_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_asin: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_log: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_y0: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_strtofr: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_acos: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_min: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_out_str: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_tan: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_free_cache: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_expm1: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_atanh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_dim: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_asin: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_y1: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_overflow_p: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_erf: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_clear: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_cosh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_acos: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_cosh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpc_sin: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: mpfr_set_ui_2exp: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmpz_add_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/10.2.0/cc1: __gmp_version: symbol not found
make: *** [/usr/local/ps2dev/ps2sdk/samples/Makefile.eeglobal:31: hello.o] Error 1`

Does anyone have any idea what it might be?

**Comment by Lonttu** [comment]
I have the exact same problem, and i know what's causing it.

![Screenshot 2021-03-27 131752](https://user-images.githubusercontent.com/69455665/113471225-bf794100-9463-11eb-835d-1226c84fe382.png)

Turns out, the packages mpc, mpfr and gmp are either broken or missing in apt-get. Please correct me if i'm wrong or missing something.
![Screenshot 2021-04-03 100918](https://user-images.githubusercontent.com/69455665/113471399-aa50e200-9464-11eb-8039-0b30575d7ba2.png)

**Comment by fjtrujy** [comment]
You are using wrong library names

Take a look to the CI workflow,

https://github.com/ps2dev/ps2dev/blob/master/.github/workflows/compilation.yml#L25

**Comment by Lonttu** [comment]
I see, so that's why they are missing in apt-get. So i was wrong about them being missing.

But anyway, i should probably state that the above picture is from the docker image trying to build the hello sample, and the below one is me demonstrating that the packages are missing, since disproven.

**Comment by fjtrujy** [comment]
@Lonttu I think that the issue was resolved right?
Can you close then the issue?
Thanks

**Comment by madebr** [comment]
I can reproduce this problem locally and [on github actions](https://github.com/madebr/librw/runs/3029064557?check_suite_focus=true).
This can be fixed by installing `mpc1` and `mpfr`.

I added the following to my github workflow:
```
apk add mpc1 mpfr
```

Local log:
```
docker pull ps2dev/ps2dev:latest
docker run -ti ps2dev/ps2dev:latest sh
/ # echo "int main() {}">/tmp/tmp.c
/ # $PS2DEV/ee/bin/mips64r5900el-ps2-elf-gcc /tmp/tmp.c
Error loading shared library libmpc.so.3: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
Error loading shared library libmpfr.so.6: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
Error loading shared library libgmp.so.10: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_hypot: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_cmp: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_emin: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_atan: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_get_version: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_exp2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_asinh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_max: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_log1p: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_snprintf: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_div: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_cbrt: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_atan2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_mul: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_j0: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_underflow_p: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_set_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_exp10: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_exp: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_pow: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_clear: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_log2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_init2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_erangeflag: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_pow: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_lgamma: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_asinh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sqrt_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_inits: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_cos: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_gamma: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_remainder: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_log10: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_tanh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_add: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_clears: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_set: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_get_version: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_si_2exp: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_sizeinbase: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_yn: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_str: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_free_str: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sqrt: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_erfc: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_j1: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_inf: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sin_cos: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_remquo: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sin: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_inits2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_fdiv_q: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_emax: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_tan: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_tanh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_get_str: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_acosh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_sinh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_atan: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_acosh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_init2: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_jn: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_clear_flags: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_clear: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_export: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_com: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_number_p: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_log: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_exp: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_cos: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_swap: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_nan: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_import: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_sub_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_fma: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sinh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sub: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_init_set: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_sub: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_atanh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_init: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_sqrt: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sub_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_asin: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_log: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_y0: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_strtofr: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_acos: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_min: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_out_str: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_tan: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_free_cache: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_expm1: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_atanh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_dim: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_asin: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_y1: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_overflow_p: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_erf: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_clear: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_cosh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_acos: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_cosh: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_sin: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_ui_2exp: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_add_ui: symbol not found
Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmp_version: symbol not found
/ # 
```

**Comment by fjtrujy** [comment]
> I can reproduce this problem locally and [on github actions](https://github.com/madebr/librw/runs/3029064557?check_suite_focus=true).
> This can be fixed by installing `mpc1` and `mpfr`.
> 
> I added the following to my github workflow:
> 
> ```
> apk add mpc1 mpfr
> ```
> 
> So I think the docker image is broken.
> 
> Local log:
> 
> ```
> $ docker pull ps2dev/ps2dev:latest
> latest: Pulling from ps2dev/ps2dev
> Digest: sha256:fbd0f8154957ec9c3a65b2683183144d97f9e08694a5b6a9db2d01d510747e7d
> Status: Image is up to date for ps2dev/ps2dev:latest
> docker.io/ps2dev/ps2dev:latest
> $ docker run -ti ps2dev/ps2dev:latest sh
> / # echo "int main() {}">/tmp/tmp.c
> / # $PS2DEV/ee/bin/mips64r5900el-ps2-elf-gcc /tmp/tmp.c
> Error loading shared library libmpc.so.3: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
> Error loading shared library libmpfr.so.6: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
> Error loading shared library libgmp.so.10: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_hypot: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_cmp: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_emin: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_atan: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_get_version: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_exp2: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_asinh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_max: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_log1p: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_snprintf: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_div: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_cbrt: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_atan2: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_mul: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_j0: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_underflow_p: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_set_ui: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_exp10: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_exp: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_pow: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_clear: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_log2: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_init2: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_erangeflag: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_pow: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_lgamma: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_asinh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sqrt_ui: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_inits: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_cos: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_gamma: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_remainder: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_log10: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_tanh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_add: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_clears: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_set: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_get_version: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_si_2exp: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_sizeinbase: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_yn: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_str: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_free_str: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sqrt: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_erfc: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_j1: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_inf: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sin_cos: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_remquo: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sin: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_inits2: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_fdiv_q: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_emax: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_tan: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_tanh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_get_str: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_acosh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_ui: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_sinh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_atan: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_acosh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_init2: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_jn: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_clear_flags: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_clear: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_export: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_com: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_number_p: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_log: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_exp: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_cos: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_swap: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_nan: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_import: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_sub_ui: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_fma: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sinh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sub: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_init_set: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_sub: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_atanh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_init: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_sqrt: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_sub_ui: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_asin: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_log: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_y0: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_strtofr: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_acos: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_min: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_out_str: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_tan: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_free_cache: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_expm1: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_atanh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_dim: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_asin: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_y1: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_overflow_p: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_erf: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_clear: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_cosh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_acos: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_cosh: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpc_sin: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: mpfr_set_ui_2exp: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmpz_add_ui: symbol not found
> Error relocating /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1: __gmp_version: symbol not found
> / # 
> ```

So this is NOT definitely an issue in the `PS2DEV` or docker issue.

Dockers are sent with the less and minimal executables to make it work. The main objective is to have dockers really tiny because this is crucial for initialization times (on Alpine images).

Watching your repo, 
https://github.com/madebr/librw/runs/3029064557?check_suite_focus=true
It actually confirms what I mean, is your piece of software the one that requires `gmp`, `mpc1` and `mpfr`, so you are the one that needs to add this in your compilation steps (on the same way than `cmake` for instance)

Thanks

**Comment by madebr** [comment]
@fjtrujy 
> So this is NOT definitely an issue in the `PS2DEV` or docker image.

I still think there is a problem with the docker i
Run these commands to download and start a docker instance:
```
docker pull ps2dev/ps2dev:latest
docker run -ti ps2dev/ps2dev:latest sh
```

Run these commands inside the docker instance:
```
echo "int main() {}">/tmp/tmp.c
mips64r5900el-ps2-elf-gcc /tmp/tmp.c
```

> Dockers are sent with the less and minimal executables to make it work. The main objective is to have dockers really tiny because this is crucial for initialization times (on Alpine images).

That's true.
But here, running `mips64r5900el-ps2-elf-gcc` without arguments succeeds, but as soon as you start compiling a source, it fails.

gmp, mpc and mpfr are required dependencies of gcc.
See https://gcc.gnu.org/wiki/InstallingGCC



> 
> Watching your repo,
> https://github.com/madebr/librw/runs/3029064557?check_suite_focus=true
> It actually confirms what I mean, is your piece of software the one that requires `gmp`, `mpc1` and `mpfr`, so you are the one that needs to add this in your compilation steps (on the same way than `cmake` for instance)
> 
> Thanks

**Comment by fjtrujy** [comment]
Hello,
I know why it is failing, and I understand your point, but I still think that due of nature of `Alpine` it shouldn't go to the docker.

So the only dependency that you should add into the docker is:
`apk add build-base`

In the same way, we don't even have `bash` in the docker either.

Why I'm doing this, is because after doing some investigations, is FASTER to start a tiny docker image and then install dependencies, than to start a docker with the dependencies installed.

This is in my opinion the nature of how Alpine works, because otherwise where do we stop?  `build-base, cmake, bash, git, wget .....`

**Comment by fjtrujy** [comment]
I forgot it, here you have an example of a dummy `Hello World`, where you can see what are the installed tools in the docker
https://github.com/fjtrujy/helloWorldPS2

**Comment by madebr** [comment]
> Hello,
> I know why it is failing, and I understand your point, but I still think that due of nature of `Alpine` it shouldn't go to the docker.
> 
> So the only dependency that you should add into the docker is:
> `apk add build-base`
> 
> In the same way, we don't even have `bash` in the docker either.
> 
> Why I'm doing this, is because after doing some investigations, is FASTER to start a tiny docker image and then install dependencies, than to start a docker with the dependencies installed.
> 
> This is in my opinion the nature of how Alpine works, because otherwise where do we stop? `build-base, cmake, bash, git, wget .....`


Thanks for explaining your method of thinking.
I will add `apk add build-base` to the github actions.
Is this documented somewhere?

**Comment by fjtrujy** [comment]
> > Hello,
> > I know why it is failing, and I understand your point, but I still think that due of nature of `Alpine` it shouldn't go to the docker.
> > So the only dependency that you should add into the docker is:
> > `apk add build-base`
> > In the same way, we don't even have `bash` in the docker either.
> > Why I'm doing this, is because after doing some investigations, is FASTER to start a tiny docker image and then install dependencies, than to start a docker with the dependencies installed.
> > This is in my opinion the nature of how Alpine works, because otherwise where do we stop? `build-base, cmake, bash, git, wget .....`
> 
> Thanks for explaining your method of thinking.
> I will add `apk add build-base` to the github actions.
> Is this documented somewhere?

Hello again,
Thanks for making such a kind of question they are really interesting.

It is not documented sorry. 😢 

Let me tell you a deeper explanation of why the docker is so "dummy".

My idea is to have in the docker all the needed things to start working with the `PS2 Dev` without any additional compilation,
and I say, compilation, and not installation. So imagine:

- A user that just picks the docker for executing `ps2-packer`. Does this user need to install anything? Probably not.

- A user that just picks the docker for compiling assembly files. Does this user need to install anything? Not sure, it depends about what `binutils requires`

- A user that just picks the docker for compiling his HUGE project. Does this user need to install anything?  Probably he needs to install, `bash, cmake, git....`

In all the scenarios, the docker image is ready to install the needed dependencies by the project itself and play.

Maybe I'm mistaking but I think this is how `Alpine` does for distributing their docker images: 
"Minimum things to make everything work, and then you as a user just need to install your required things."


Anyway, coming back to your original question, we're always open to improving documentation, so **PRs are more than welcome!**

**Comment by terremoth** [comment]
@fjtrujy maybe we can add at README.md (or in a INSTALL.md page) these compilation.yml codes, something like:

## Ubuntu/Debian install
```bash 
sudo apt install ...
```

## Alpine:
```bash 
apk add ... 
```

## Fedora/CentOS
```
sudo dnf install ...
```

I see everytime people having basics problems with installing because lacked which exactly libraries should they install on each operating system

What you guys think about?

**Comment by fjtrujy** [comment]
> @fjtrujy maybe we can add at README.md (or in a INSTALL.md page) these compilation.yml codes, something like:
> 
> ## Ubuntu/Debian install
> ```shell
> sudo apt install ...
> ```
> 
> ## Alpine:
> ```shell
> apk add ... 
> ```
> 
> ## Fedora/CentOS
> ```
> sudo dnf install ...
> ```
> 
> I see everytime people having basics problems with installing because lacked which exactly libraries should they install on each operating system. Seems a lot obscure people had to enter on compilation.yml to see which software they need to install.
> 
> What you guys think about? I can help with

The issue that @madebr was suffering is totally unrelated to this.
You're proposing improvements for identifying libraries names to install per Operating system and his issue is about `docker isn't working as he expected`

Anyway, again **PRs are more than welcome**

**Comment by dirsors** [comment]
For Ubuntu:
`apt-get -y install gcc clang make cmake patch git texinfo flex bison gettext wget libgsl-dev libgmp3-dev libmpfr-dev libmpc-dev zlib1g-dev`

**Comment by fjtrujy** [comment]
Closing this issue as it was resolved time ago!

**Comment by VinegarLove** [comment]
@fjtrujy Sorry for necroposting on this one.

I have some questions about the gcc required libraries gmp mpc1 mpfr.
I still have the following errors, as i expected.

```
Error loading shared library libmpc.so.3: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
Error loading shared library libmpfr.so.6: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
Error loading shared library libgmp.so.10: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
```

Now, using the apk to install the libs...

```apk add mpc1 mpfr```

But doesn't this mean that I'm pulling the libraries **for the GCC of the Alpine architecture** and not the one for the PS2 toolchain's GCC?

The ELFs compile successfully, but for some reason I actually have some weird things happening on SDL2 side i compiled, related to Uint32 and number conversion.

First, `SDL_GetTicks()` should return a uint32_t millisecond values, instead the value is displayed as microseconds (not just displayed, it's returned as such)... Also libnano doesn't print anything when trying to display the value. With stdlib it works.

If possible, could you point me to the flag / command you use to compile SDL2?
I need to compile a custom version.

Thanks.

**Comment by fjtrujy** [comment]
> @fjtrujy Sorry for necroposting on this one.
> 
> I have some questions about the gcc required libraries gmp mpc1 mpfr. I still have the following errors, as i expected.
> 
> ```
> Error loading shared library libmpc.so.3: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
> Error loading shared library libmpfr.so.6: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
> Error loading shared library libgmp.so.10: No such file or directory (needed by /usr/local/ps2dev/ee/libexec/gcc/mips64r5900el-ps2-elf/11.1.0/cc1)
> ```
> 
> Now, using the apk to install the libs...
> 
> `apk add mpc1 mpfr`
> 
> But doesn't this mean that I'm pulling the libraries **for the GCC of the Alpine architecture** and not the one for the PS2 toolchain's GCC?
> 
> The ELFs compile successfully, but for some reason I actually have some weird things happening on SDL2 side i compiled, related to Uint32 and number conversion.
> 
> First, `SDL_GetTicks()` should return a uint32_t millisecond values, instead the value is displayed as microseconds (not just displayed, it's returned as such)... Also libnano doesn't print anything when trying to display the value. With stdlib it works.
> 
> If possible, could you point me to the flag / command you use to compile SDL2? I need to compile a custom version.
> 
> Thanks.

To install the dependencies is normal, the `ps2dev:latest` toolchain is thought to be a layer similar as `alpine:latest`. The dependencies you are installing as just dependencies needed by the GCC (no matter is target is MIPS, or x86).



Then let me investigate the SDL issue I thought I solved it as you can see here:
https://github.com/libsdl-org/SDL/pull/10125

Then compilation, you can check how to compile in the YML files there are in the repo, it uses cmake.

I don’t know what you mean with libnano, if you mean libc_nano, it should work well too.

**Comment by VinegarLove** [comment]
> To install the dependencies is normal, the ps2dev:latest toolchain is thought to be a layer
> similar as alpine:latest. The dependencies you are installing as just dependencies needed by > the GCC (no matter is target is MIPS, or x86).

Perfect!

> Then let me investigate the SDL issue I thought I solved it as you can see here:
> https://github.com/libsdl-org/SDL/pull/10125

About that, I compiled the latest stable release of SDL2.0 about 1 week ago.
I don't remember if it's the 2.30.11 or 2.30.10. I believe it was the latest one.

My custom version modified this file:
[SDL_render_ps2.c](https://github.com/libsdl-org/SDL/blob/SDL2/src/render/ps2/SDL_render_ps2.c)

to have it return the struct below using a new function called `SDL_GetRendererDriverData`.
I needed it because I wanted to have the gsGlobal context of the gsKit library.


```
// struct from the file
typedef struct
{
    GSGLOBAL *gsGlobal;
    uint64_t drawColor;
    SDL_Rect *viewport;
    int32_t vsync_callback_id;
    uint8_t vsync; /* 0 (Disabled), 1 (Enabled), 2 (Dynamic) */
} PS2_RenderData;

// usage
PS2_RenderData *data = (PS2_RenderData *)SDL_GetRendererDriverData(renderer);
```

I compiled it like this:
```
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PS2DEV/ps2sdk/ps2dev.cmake -DCMAKE_INSTALL_PREFIX=$PS2DEV/ps2sdk/ports
```

> Then compilation, you can check how to compile in the YML files there are in the repo, it uses cmake.

Thank you very much! I'll check them out.

> I don’t know what you mean with libnano, if you mean libc_nano, it should work well too.

Yes, sorry. I meant libc_nano. When writing this:

```
printf("delta time: %u\n", deltaTime);
```

It printed an empty string when compiled my ELF with libc_nano.

I'll attach the Makefile that I'm using. I'm not sure if it's correct, I've taken it from the sample since they very well configured.

[Makefile.txt](https://github.com/user-attachments/files/18383885/Makefile.txt)
